pipeline {
    agent any

    tools {
        nodejs "NodeJS" // Configure NodeJS in Jenkins global tools
    }

    environment {
        IMAGE_NAME = "react-app"
        SONAR_TOKEN = credentials('SONARQUBE_TOKEN') // Add in Jenkins credentials
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Payalingle/React_Application.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Code Analysis - SonarQube') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh '''
                        npm install -g sonarqube-scanner
                        sonar-scanner \
                          -Dsonar.projectKey=ReactApp \
                          -Dsonar.sources=. \
                          -Dsonar.host.url=$SONAR_HOST_URL \
                          -Dsonar.login=$SONAR_TOKEN
                    '''
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Scan with Trivy') {
            steps {
                sh 'trivy image --severity HIGH,CRITICAL --exit-code 0 $IMAGE_NAME'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run -d -p 8000:80 $IMAGE_NAME'
            }
        }
    }
}
